# Generated by Django 3.2 on 2022-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='../../media/img_post_perdido.png', upload_to=''),
        ),
    ]
