# Generated by Django 3.2 on 2022-06-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default='image1.png', upload_to='posts/posts_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='image2.png', upload_to='posts/posts_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='image3.png', upload_to='posts/posts_image'),
        ),
    ]
