# Generated by Django 3.2 on 2022-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='buscandog/media/img_post_perdido.png', upload_to=''),
        ),
    ]
